//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программным средством.
//     Версия среды выполнения: 4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
//     код создан повторно.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapEdit.Properties
{


	/// <summary>
	///   Класс ресурсов со строгим типом для поиска локализованных строк и пр.
	/// </summary>
	// Этот класс был автоматически создан при помощи StronglyTypedResourceBuilder
	// класс с помощью таких средств, как ResGen или Visual Studio.
	// Для добавления или удаления члена измените файл .ResX, а затем перезапустите ResGen
	// с параметром /str или заново постройте свой VS-проект.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
		///   Возврат кэшированного экземпляра ResourceManager, используемого этим классом.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if ((resourceMan == null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapEdit.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Переопределяет свойство CurrentUICulture текущего потока для всех
		///   подстановки ресурсов с помощью этого класса ресурсов со строгим типом.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap box
		{
			get
			{
				object obj = ResourceManager.GetObject("box", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Bush
		{
			get
			{
				object obj = ResourceManager.GetObject("Bush", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Grass
		{
			get
			{
				object obj = ResourceManager.GetObject("grass", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tree2
		{
			get
			{
				object obj = ResourceManager.GetObject("tree2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap marker
		{
			get
			{
				object obj = ResourceManager.GetObject("marker", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap marker2
		{
			get
			{
				object obj = ResourceManager.GetObject("marker2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
